// ==========================================================================
// 📖 华文智能互动学习阅读器 - 词汇数据库 (data.js)
// ==========================================================================

const lessonTitle = "写在雪地上的书";

const lessonData = [
    // ===== 第1段 =====
    ["野兽", "yě shòu", "wild beasts", "binatang buas"],
    ["走来走去", "zǒu lái zǒu qù", "walk back and forth", "berjalan ke sana ke mari"],
    ["，", "", "", ""],
    ["把", "bǎ", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["留在", "liú zài", "leave on", "tinggal di"],
    ["雪地", "xuě dì", "snowy ground", "tanah bersalji"],
    ["上", "shàng", "on", "atas"],
    ["。", "", "", ""],
    ["那些", "nà xiē", "those", "itu semua"],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["并不是", "bìng bù shì", "are not", "bukanlah"],
    ["一下子", "yī xià zi", "at once", "sekali gus"],
    ["都", "dōu", "all", "semua"],
    ["能", "néng", "can", "boleh"],
    ["弄清楚", "nòng qīng chu", "figure out", "memahami"],
    ["的", "de", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    // ===== 第2段 =====
    ["左边", "zuǒ biān", "left side", "sebelah kiri"],
    ["，", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["矮树林", "ǎi shù lín", "low woods", "hutan rendah"],
    ["下面", "xià miàn", "below", "bawah"],
    ["出现", "chū xiàn", "appear", "muncul"],
    ["的", "de", "", ""],
    ["是", "shì", "is", "ialah"],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["。", "", "", ""],
    ["后脚", "hòu jiǎo", "hind legs", "kaki belakang"],
    ["留下", "liú xià", "leave", "tinggalkan"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["是", "shì", "is", "ialah"],
    ["长条形", "cháng tiáo xíng", "long strip shape", "berbentuk panjang"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["前脚", "qián jiǎo", "front legs", "kaki depan"],
    ["留下", "liú xià", "leave", "tinggalkan"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["是", "shì", "is", "ialah"],
    ["小圆形", "xiǎo yuán xíng", "small round shape", "berbentuk bulat kecil"],
    ["的", "de", "", ""],
    ["。", "", "", ""],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["多半", "duō bàn", "mostly", "kebanyakan"],
    ["留在", "liú zài", "left on", "tinggal di"],
    ["旷野", "kuàng yě", "open field", "padang terbuka"],
    ["间", "jiān", "between", "di antara"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    // ===== 第3段 =====
    ["右边", "yòu biān", "right side", "sebelah kanan"],
    ["，", "", "", ""],
    ["是", "shì", "is", "ialah"],
    ["另一种", "lìng yī zhǒng", "another kind", "satu lagi jenis"],
    ["野兽", "yě shòu", "wild beast", "binatang buas"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["，", "", "", ""],
    ["要", "yào", "relatively", "agak"],
    ["略", "lüè", "slightly", "sedikit"],
    ["大", "dà", "big", "besar"],
    ["一点", "yī diǎn", "a bit", "sedikit"],
    ["，", "", "", ""],
    ["雪地", "xuě dì", "snowy ground", "tanah bersalji"],
    ["上", "shàng", "on", "atas"],
    ["留下", "liú xià", "leave", "tinggalkan"],
    ["它", "tā", "its", "ia"],
    ["锋利", "fēng lì", "sharp", "tajam"],
    ["爪子", "zhuǎ zi", "claws", "kuku"],
    ["的", "de", "", ""],
    ["深度", "shēn dù", "depth", "kedalaman"],
    ["，", "", "", ""],
    ["这是", "zhè shì", "this is", "ini adalah"],
    ["狐狸", "hú lí", "fox", "musang"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["。", "", "", ""],
    ["而", "ér", "and", "dan"],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["的", "de", "", ""],
    ["另一边", "lìng yī biān", "the other side", "sebelah lagi"],
    ["还", "hái", "still", "masih"],
    ["有", "yǒu", "have", "ada"],
    ["一串", "yī chuàn", "a string of", "serangkaian"],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["，", "", "", ""],
    ["那", "nà", "that", "itu"],
    ["也", "yě", "also", "juga"],
    ["是", "shì", "is", "ialah"],
    ["狐狸", "hú lí", "fox", "musang"],
    ["留下", "liú xià", "leave", "tinggalkan"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["只不过", "zhǐ bù guò", "only that", "hanya saja"],
    ["这只", "zhè zhī", "this", "ini"],
    ["狐狸", "hú lí", "fox", "musang"],
    ["是", "shì", "is", "ialah"],
    ["向后", "xiàng hòu", "backward", "ke belakang"],
    ["跑", "pǎo", "run", "lari"],
    ["的", "de", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    // ===== 第4段 =====
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["在", "zài", "in", "di"],
    ["旷野", "kuàng yě", "open field", "padang terbuka"],
    ["里", "lǐ", "in", "dalam"],
    ["兜了", "dōu le", "made", "membuat"],
    ["个", "gè", "", ""],
    ["圈子", "quān zi", "circle", "bulatan"],
    ["，", "", "", ""],
    ["狐狸", "hú lí", "fox", "musang"],
    ["也", "yě", "also", "juga"],
    ["跟着", "gēn zhe", "follow", "mengikuti"],
    ["兜了", "dōu le", "made", "membuat"],
    ["个", "gè", "", ""],
    ["圈子", "quān zi", "circle", "bulatan"],
    ["。", "", "", ""],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["向", "xiàng", "towards", "ke arah"],
    ["另一个", "lìng yī gè", "another", "satu lagi"],
    ["方向", "fāng xiàng", "direction", "arah"],
    ["延伸", "yán shēn", "extend", "memanjang"],
    ["，", "", "", ""],
    ["狐狸", "hú lí", "fox", "musang"],
    ["也", "yě", "also", "juga"],
    ["跟着", "gēn zhe", "follow", "mengikuti"],
    ["。", "", "", ""],
    ["两串", "liǎng chuàn", "two strings", "dua rangkaian"],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["在", "zài", "in", "di"],
    ["旷野", "kuàng yě", "open field", "padang terbuka"],
    ["中", "zhōng", "in", "dalam"],
    ["不见了", "bù jiàn le", "disappeared", "hilang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    // ===== 第5段 =====
    ["瞧", "qiáo", "Look", "Lihat"],
    ["，", "", "", ""],
    ["在", "zài", "on", "di"],
    ["另一边", "lìng yī biān", "the other side", "sebelah lagi"],
    ["又", "yòu", "again", "lagi"],
    ["出现", "chū xiàn", "appear", "muncul"],
    ["了", "le", "", ""],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["，", "", "", ""],
    ["一下子", "yī xià zi", "suddenly", "sekali gus"],
    ["不见了", "bù jiàn le", "disappeared", "hilang"],
    ["，", "", "", ""],
    ["一下", "yī xià", "suddenly", "sekali"],
    ["又", "yòu", "again", "lagi"],
    ["出现", "chū xiàn", "appear", "muncul"],
    ["了", "le", "", ""],
    ["……", "", "", ""],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["走着", "zǒu zhe", "walking", "berjalan"],
    ["，", "", "", ""],
    ["走着", "zǒu zhe", "walking", "berjalan"],
    ["，", "", "", ""],
    ["后来", "hòu lái", "later", "kemudian"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["不见了", "bù jiàn le", "disappeared", "hilang"],
    ["，", "", "", ""],
    ["就", "jiù", "just", "seperti"],
    ["像是", "xiàng shì", "as if", "seperti"],
    ["钻进", "zuān jìn", "burrow into", "masuk ke dalam"],
    ["了", "le", "", ""],
    ["地里", "dì lǐ", "ground", "dalam tanah"],
    ["！", "", "", ""],
    ["在", "zài", "at", "di"],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["消失", "xiāo shī", "disappear", "hilang"],
    ["的", "de", "", ""],
    ["地方", "dì fang", "place", "tempat"],
    ["，", "", "", ""],
    ["留下", "liú xià", "leave", "tinggalkan"],
    ["一个", "yī gè", "a", "satu"],
    ["乱糟糟", "luàn zāo zāo", "messy", "bersepah"],
    ["的", "de", "", ""],
    ["雪窝", "xuě wō", "snow pit", "lubang salji"],
    ["，", "", "", ""],
    ["四面", "sì miàn", "all sides", "empat penjuru"],
    ["有", "yǒu", "have", "ada"],
    ["一条条", "yī tiáo tiáo", "strip after strip", "jalur demi jalur"],
    ["光滑", "guāng huá", "smooth", "licin"],
    ["的", "de", "", ""],
    ["痕迹", "hén jì", "traces", "kesan"],
    ["，", "", "", ""],
    ["仿佛", "fǎng fú", "as if", "seolah-olah"],
    ["是", "shì", "is", "ialah"],
    ["人", "rén", "person", "orang"],
    ["用", "yòng", "use", "menggunakan"],
    ["手指头", "shǒu zhǐ tou", "finger", "jari"],
    ["抹过", "mǒ guò", "wipe", "mengelap"],
    ["似的", "sì de", "as if", "seperti"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    // ===== 第6段 =====
    ["狐狸", "hú lí", "fox", "musang"],
    ["哪去", "nǎ qù", "where gone", "ke mana pergi"],
    ["了", "le", "", ""],
    ["？", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    // ===== 第7段 =====
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["哪去", "nǎ qù", "where gone", "ke mana pergi"],
    ["了", "le", "", ""],
    ["？", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    // ===== 第8段 =====
    ["我们", "wǒ men", "we", "kita"],
    ["来", "lái", "come", "datang"],
    ["看", "kàn", "look", "lihat"],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    // ===== 第9段 =====
    ["这是", "zhè shì", "This is", "Ini adalah"],
    ["一座", "yī zuò", "a", "sebuah"],
    ["矮树林", "ǎi shù lín", "low woods", "hutan rendah"],
    ["。", "", "", ""],
    ["这里", "zhè lǐ", "here", "di sini"],
    ["的", "de", "", ""],
    ["树皮", "shù pí", "tree bark", "kulit kayu"],
    ["被", "bèi", "by", "oleh"],
    ["撕开", "sī kāi", "torn open", "dikoyak"],
    ["，", "", "", ""],
    ["挂", "guà", "hang", "tergantung"],
    ["了", "le", "", ""],
    ["下来", "xià lái", "down", "turun"],
    ["。", "", "", ""],
    ["矮树", "ǎi shù", "low tree", "pokok rendah"],
    ["留下", "liú xià", "leave", "tinggalkan"],
    ["许多", "xǔ duō", "many", "banyak"],
    ["踩踏", "cǎi tà", "trample", "pijakan"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["，", "", "", ""],
    ["还", "hái", "also", "juga"],
    ["伴有", "bàn yǒu", "accompanied by", "disertai dengan"],
    ["泥污", "ní wū", "mud stains", "kesan lumpur"],
    ["，", "", "", ""],
    ["这是", "zhè shì", "this is", "ini adalah"],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["。", "", "", ""],
    ["这只", "zhè zhī", "this", "ini"],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["吃", "chī", "eat", "makan"],
    ["嫩叶", "nèn yè", "tender leaves", "daun muda"],
    ["吃", "chī", "eat", "makan"],
    ["树皮", "shù pí", "tree bark", "kulit kayu"],
    ["，", "", "", ""],
    ["显然", "xiǎn rán", "obviously", "jelas"],
    ["，", "", "", ""],
    ["是", "shì", "is", "ialah"],
    ["它", "tā", "its", "ia"],
    ["的", "de", "", ""],
    ["肚子", "dù zi", "stomach", "perut"],
    ["饿了", "è le", "hungry", "lapar"],
    ["。", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["用", "yòng", "use", "menggunakan"],
    ["后腿", "hòu tuǐ", "hind legs", "kaki belakang"],
    ["站立", "zhàn lì", "stand", "berdiri"],
    ["起来", "qǐ lái", "up", "naik"],
    ["，", "", "", ""],
    ["用", "yòng", "use", "menggunakan"],
    ["牙", "yá", "teeth", "gigi"],
    ["撕下", "sī xià", "tear off", "mengoyak"],
    ["一块", "yī kuài", "a piece", "sepotong"],
    ["树皮", "shù pí", "tree bark", "kulit kayu"],
    ["，", "", "", ""],
    ["在", "zài", "in", "di"],
    ["嘴里", "zuǐ lǐ", "mouth", "mulut"],
    ["嚼细", "jiáo xì", "chew finely", "kunyah halus"],
    ["，", "", "", ""],
    ["走了", "zǒu le", "walked", "berjalan"],
    ["几步", "jǐ bù", "a few steps", "beberapa langkah"],
    ["，", "", "", ""],
    ["又", "yòu", "again", "lagi"],
    ["撕下", "sī xià", "tear off", "mengoyak"],
    ["一块", "yī kuài", "a piece", "sepotong"],
    ["树皮", "shù pí", "tree bark", "kulit kayu"],
    ["，", "", "", ""],
    ["吃饱了", "chī bǎo le", "eaten full", "kenyang"],
    ["，", "", "", ""],
    ["想", "xiǎng", "want", "mahu"],
    ["睡觉", "shuì jiào", "sleep", "tidur"],
    ["了", "le", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    // ===== 第10段 =====
    ["它", "tā", "It", "Ia"],
    ["边跑", "biān pǎo", "run while", "sambil berlari"],
    ["边找", "biān zhǎo", "search while", "sambil mencari"],
    ["，", "", "", ""],
    ["看", "kàn", "see", "lihat"],
    ["是", "shì", "is", "adalah"],
    ["到", "dào", "to", "ke"],
    ["哪儿", "nǎ ér", "where", "di mana"],
    ["去", "qù", "go", "pergi"],
    ["躲着", "duǒ zhe", "hide", "bersembunyi"],
    ["睡觉", "shuì jiào", "sleep", "tidur"],
    ["最", "zuì", "most", "paling"],
    ["合适", "hé shì", "suitable", "sesuai"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    // ===== 第11段 =====
    ["再", "zài", "then", "kemudian"],
    ["来看", "lái kàn", "look at", "lihat"],
    ["，", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["狐狸", "hú lí", "fox", "musang"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["，", "", "", ""],
    ["就", "jiù", "just", "tepat"],
    ["在", "zài", "at", "di"],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["近旁", "jìn páng", "nearby", "berhampiran"],
    ["。", "", "", ""],
    ["事情", "shì qíng", "the matter", "perkara"],
    ["准是", "zhǔn shì", "must be", "pasti"],
    ["这样", "zhè yàng", "like this", "begini"],
    ["：", "", "", ""],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["睡了", "shuì le", "slept", "tidur"],
    ["，", "", "", ""],
    ["睡了", "shuì le", "slept", "tidur"],
    ["一个", "yī gè", "one", "satu"],
    ["钟头", "zhōng tóu", "hour", "jam"],
    ["。", "", "", ""],
    ["狐狸", "hú lí", "fox", "musang"],
    ["在", "zài", "in", "di"],
    ["旷野", "kuàng yě", "open field", "padang terbuka"],
    ["里", "lǐ", "in", "dalam"],
    ["走动", "zǒu dòng", "walk around", "berjalan-jalan"],
    ["。", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["发现", "fā xiàn", "discover", "menemui"],
    ["，", "", "", ""],
    ["地上", "dì shàng", "ground", "tanah"],
    ["有", "yǒu", "have", "ada"],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["！", "", "", ""],
    ["狐狸", "hú lí", "fox", "musang"],
    ["的", "de", "", ""],
    ["尖嘴", "jiān zuǐ", "pointed snout", "muncung tajam"],
    ["于是", "yú shì", "so", "lalu"],
    ["挨贴", "āi tiē", "press close", "rapat"],
    ["到", "dào", "to", "ke"],
    ["地面", "dì miàn", "ground", "permukaan tanah"],
    ["，", "", "", ""],
    ["走着", "zǒu zhe", "walking", "berjalan"],
    ["，", "", "", ""],
    ["嗅着", "xiù zhe", "sniffing", "menghidu"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    // ===== 第12段 =====
    ["它", "tā", "It", "Ia"],
    ["马上", "mǎ shàng", "immediately", "segera"],
    ["闻出来", "wén chū lái", "smell out", "menghidu"],
    ["，", "", "", ""],
    ["这", "zhè", "this", "ini"],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["是", "shì", "is", "ialah"],
    ["刚", "gāng", "just", "baru"],
    ["留下", "liú xià", "leave", "tinggalkan"],
    ["的", "de", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第13段

    // ===== 第13段 =====
    ["它", "tā", "It", "Ia"],
    ["沿着", "yán zhe", "along", "sepanjang"],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["追寻", "zhuī xún", "pursue", "mengejar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第14段

    // ===== 第14段 =====
    ["狐狸", "hú lí", "fox", "musang"],
    ["狡猾", "jiǎo huá", "cunning", "licik"],
    ["，", "", "", ""],
    ["可", "kě", "but", "tetapi"],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["也", "yě", "also", "juga"],
    ["不笨", "bù bèn", "not stupid", "tidak bodoh"],
    ["。", "", "", ""],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["把", "bǎ", "", ""],
    ["自己", "zì jǐ", "its own", "sendiri"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["搞", "gǎo", "make", "buat"],
    ["得", "de", "", ""],
    ["乱乱", "luàn luàn", "messy", "bersepah"],
    ["的", "de", "", ""],
    ["。", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["在", "zài", "in", "di"],
    ["旷野", "kuàng yě", "open field", "padang terbuka"],
    ["里", "lǐ", "in", "dalam"],
    ["一蹦", "yī bèng", "a jump", "satu lompatan"],
    ["一跳", "yī tiào", "a jump", "satu lompatan"],
    ["，", "", "", ""],
    ["拐了", "guǎi le", "turned", "membelok"],
    ["个", "gè", "", ""],
    ["弯", "wān", "bend", "bengkok"],
    ["，", "", "", ""],
    ["兜了", "dōu le", "made", "membuat"],
    ["个", "gè", "", ""],
    ["大圈", "dà quān", "big circle", "bulatan besar"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["穿过", "chuān guò", "cross through", "melalui"],
    ["自己", "zì jǐ", "its own", "sendiri"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["，", "", "", ""],
    ["往", "wǎng", "towards", "ke"],
    ["一边", "yī biān", "one side", "satu sisi"],
    ["跑了", "pǎo le", "ran", "lari"],
    ["。", "", "", ""],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["先是", "xiān shì", "at first", "pada mulanya"],
    ["从从容容", "cóng cóng róng róng", "unhurried", "tenang"],
    ["，", "", "", ""],
    ["不慌不忙", "bù huāng bù máng", "unhurried", "tidak tergesa-gesa"],
    ["的", "de", "", ""],
    ["，", "", "", ""],
    ["在", "zài", "when", "apabila"],
    ["没有", "méi yǒu", "not", "tidak"],
    ["觉察", "jué chá", "aware", "sedar"],
    ["有", "yǒu", "have", "ada"],
    ["灾祸", "zāi huò", "disaster", "bencana"],
    ["追随", "zhuī suí", "follow", "mengikuti"],
    ["着", "zhe", "", ""],
    ["它", "tā", "it", "ia"],
    ["时", "shí", "when", "apabila"],
    ["，", "", "", ""],
    ["它", "tā", "its", "ia"],
    ["的", "de", "", ""],
    ["步态", "bù tài", "gait", "gaya berjalan"],
    ["是", "shì", "is", "ialah"],
    ["平稳", "píng wěn", "steady", "stabil"],
    ["的", "de", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第15段

    // ===== 第15段 =====
    ["狐狸", "hú lí", "fox", "musang"],
    ["追呀", "zhuī ya", "chased", "mengejar"],
    ["，", "", "", ""],
    ["追呀", "zhuī ya", "chased", "mengejar"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["看", "kàn", "see", "lihat"],
    ["拐弯处", "guǎi wān chù", "the bend", "selekoh"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["是", "shì", "is", "ialah"],
    ["新鲜", "xīn xiān", "fresh", "segar"],
    ["的", "de", "", ""],
    ["。", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["没有", "méi yǒu", "did not", "tidak"],
    ["猜到", "cāi dào", "guess", "meneka"],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["兜了", "dōu le", "made", "membuat"],
    ["一个", "yī gè", "a", "satu"],
    ["大圈", "dà quān", "big circle", "bulatan besar"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第16段

    // ===== 第16段 =====
    ["狐狸", "hú lí", "fox", "musang"],
    ["追踪", "zhuī zōng", "track", "menjejak"],
    ["新鲜", "xīn xiān", "fresh", "segar"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["，", "", "", ""],
    ["拐弯", "guǎi wān", "turn", "membelok"],
    ["，", "", "", ""],
    ["从侧", "cóng cè", "from the side", "dari sisi"],
    ["跑呀", "pǎo ya", "ran", "berlari"],
    ["追", "zhuī", "chase", "kejar"],
    ["，", "", "", ""],
    ["追呀", "zhuī ya", "chased", "mengejar"],
    ["跑", "pǎo", "run", "lari"],
    ["，", "", "", ""],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["，", "", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["没有", "méi yǒu", "no more", "tiada"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["这下", "zhè xià", "now", "kini"],
    ["还", "hái", "still", "masih"],
    ["往", "wǎng", "towards", "ke"],
    ["哪儿", "nǎ ér", "where", "mana"],
    ["追", "zhuī", "chase", "kejar"],
    ["？", "", "", ""],

    ["\n", "", "", ""], // 👈 第17段

    // ===== 第17段 =====
    ["其实", "qí shí", "actually", "sebenarnya"],
    ["，", "", "", ""],
    ["这是", "zhè shì", "this is", "ini adalah"],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["的", "de", "", ""],
    ["又", "yòu", "another", "satu lagi"],
    ["一个", "yī gè", "a", "satu"],
    ["新花招", "xīn huā zhāo", "new trick", "muslihat baru"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第18段

    // ===== 第18段 =====
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["兜了", "dōu le", "made", "membuat"],
    ["个", "gè", "", ""],
    ["圈", "quān", "circle", "bulatan"],
    ["，", "", "", ""],
    ["穿过", "chuān guò", "cross through", "melalui"],
    ["自己", "zì jǐ", "its own", "sendiri"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["，", "", "", ""],
    ["往", "wǎng", "towards", "ke"],
    ["前走", "qián zǒu", "walk forward", "berjalan ke hadapan"],
    ["一段", "yī duàn", "a distance", "satu jarak"],
    ["，", "", "", ""],
    ["又", "yòu", "again", "lagi"],
    ["顺着", "shùn zhe", "along", "mengikuti"],
    ["自己", "zì jǐ", "its own", "sendiri"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["往后走", "wǎng hòu zǒu", "walk backward", "berjalan ke belakang"],
    ["。", "", "", ""],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["这回", "zhè huí", "this time", "kali ini"],
    ["走", "zǒu", "walk", "berjalan"],
    ["得", "de", "", ""],
    ["很", "hěn", "very", "sangat"],
    ["小心", "xiǎo xīn", "careful", "berhati-hati"],
    ["，", "", "", ""],
    ["很", "hěn", "very", "sangat"],
    ["仔细", "zǐ xì", "meticulous", "teliti"],
    ["，", "", "", ""],
    ["每", "měi", "every", "setiap"],
    ["一步", "yī bù", "step", "langkah"],
    ["都", "dōu", "all", "semua"],
    ["踩着", "cǎi zhe", "step on", "memijak"],
    ["原来", "yuán lái", "original", "asal"],
    ["自己", "zì jǐ", "its own", "sendiri"],
    ["留下", "liú xià", "leave", "tinggalkan"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第19段

    // ===== 第19段 =====
    ["狐狸", "hú lí", "fox", "musang"],
    ["站着", "zhàn zhe", "standing", "berdiri"],
    ["，", "", "", ""],
    ["站着", "zhàn zhe", "standing", "berdiri"],
    ["，", "", "", ""],
    ["接着", "jiē zhe", "then", "kemudian"],
    ["往回走", "wǎng huí zǒu", "walk back", "berjalan balik"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第20段

    // ===== 第20段 =====
    ["又", "yòu", "again", "lagi"],
    ["走到", "zǒu dào", "walk to", "berjalan ke"],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["交叉", "jiāo chā", "intersect", "bersilang"],
    ["的", "de", "", ""],
    ["地方", "dì fang", "place", "tempat"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第21段

    // ===== 第21段 =====
    ["它", "tā", "It", "Ia"],
    ["顺着", "shùn zhe", "along", "mengikuti"],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["兜了", "dōu le", "made", "membuat"],
    ["一个", "yī gè", "a", "satu"],
    ["圈", "quān", "circle", "bulatan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第22段

    // ===== 第22段 =====
    ["它", "tā", "It", "Ia"],
    ["走呀", "zǒu ya", "walked", "berjalan"],
    ["，", "", "", ""],
    ["走呀", "zǒu ya", "walked", "berjalan"],
    ["，", "", "", ""],
    ["看出", "kàn chū", "see through", "nampak"],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["在", "zài", "is", "sedang"],
    ["蒙骗", "méng piàn", "deceive", "menipu"],
    ["它", "tā", "it", "ia"],
    ["，", "", "", ""],
    ["引", "yǐn", "lure", "memancing"],
    ["它", "tā", "it", "ia"],
    ["上当", "shàng dàng", "be fooled", "tertipu"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["不知道", "bù zhī dào", "not know", "tidak tahu"],
    ["该", "gāi", "should", "patut"],
    ["往", "wǎng", "towards", "ke"],
    ["哪个", "nǎ gè", "which", "mana satu"],
    ["方向", "fāng xiàng", "direction", "arah"],
    ["才能", "cái néng", "can", "baru boleh"],
    ["找到", "zhǎo dào", "find", "menemui"],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第23段

    // ===== 第23段 =====
    ["它", "tā", "It", "Ia"],
    ["打了", "dǎ le", "gave", "memberi"],
    ["个", "gè", "", ""],
    ["响鼻", "xiǎng bí", "snort", "dengus"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "lalu"],
    ["进", "jìn", "enter", "masuk"],
    ["森林", "sēn lín", "forest", "hutan"],
    ["干", "gàn", "do", "buat"],
    ["它", "tā", "its", "ia"],
    ["自个儿", "zì gěr", "own", "sendiri"],
    ["的", "de", "", ""],
    ["事情", "shì qíng", "business", "urusan"],
    ["去了", "qù le", "went", "pergi"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第24段

    // ===== 第24段 =====
    ["事情", "shì qíng", "The matter", "Perkara"],
    ["就是", "jiù shì", "is", "adalah"],
    ["这样", "zhè yàng", "like this", "begini"],
    ["的", "de", "", ""],
    ["：", "", "", ""],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["在", "zài", "on", "di"],
    ["同一", "tóng yī", "same", "sama"],
    ["串", "chuàn", "string", "rangkaian"],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["上", "shàng", "on", "atas"],
    ["走了", "zǒu le", "walked", "berjalan"],
    ["两次", "liǎng cì", "twice", "dua kali"],
    ["，", "", "", ""],
    ["向前", "xiàng qián", "forward", "ke hadapan"],
    ["一次", "yī cì", "once", "sekali"],
    ["，", "", "", ""],
    ["又", "yòu", "again", "lagi"],
    ["踩着", "cǎi zhe", "step on", "memijak"],
    ["自己", "zì jǐ", "its own", "sendiri"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["往后走", "wǎng hòu zǒu", "walk backward", "berjalan ke belakang"],
    ["一次", "yī cì", "once", "sekali"],
    ["。", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["在", "zài", "in", "di"],
    ["没有", "méi yǒu", "not", "tidak"],
    ["兜完", "dōu wán", "finish making", "habis membuat"],
    ["一个", "yī gè", "a", "satu"],
    ["圈子", "quān zi", "circle", "bulatan"],
    ["的", "de", "", ""],
    ["时候", "shí hou", "when", "apabila"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "lalu"],
    ["钻进", "zuān jìn", "burrow into", "masuk ke dalam"],
    ["并", "bìng", "and", "dan"],
    ["穿过", "chuān guò", "cross through", "melalui"],
    ["一个", "yī gè", "a", "satu"],
    ["雪堆", "xuě duī", "snow pile", "longgokan salji"],
    ["，", "", "", ""],
    ["从", "cóng", "from", "dari"],
    ["另一个", "lìng yī gè", "another", "satu lagi"],
    ["方向", "fāng xiàng", "direction", "arah"],
    ["跑掉", "pǎo diào", "run away", "lari"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["跳着", "tiào zhe", "jumping", "melompat"],
    ["穿过", "chuān guò", "cross through", "melalui"],
    ["矮树林", "ǎi shù lín", "low woods", "hutan rendah"],
    ["，", "", "", ""],
    ["接着", "jiē zhe", "then", "kemudian"],
    ["就", "jiù", "then", "lalu"],
    ["在", "zài", "in", "di"],
    ["一堆", "yī duī", "a pile", "setimbun"],
    ["干树枝", "gān shù zhī", "dry branches", "dahan kering"],
    ["底下", "dǐ xià", "under", "bawah"],
    ["悄悄", "qiāo qiāo", "quietly", "diam-diam"],
    ["躺着", "tǎng zhe", "lying", "berbaring"],
    ["。", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["躺在", "tǎng zài", "lie at", "berbaring di"],
    ["那里", "nà lǐ", "there", "sana"],
    ["，", "", "", ""],
    ["一直", "yī zhí", "always", "sentiasa"],
    ["躺到", "tǎng dào", "lie until", "berbaring sehingga"],
    ["狐狸", "hú lí", "fox", "musang"],
    ["循着", "xún zhe", "following", "mengikuti"],
    ["它", "tā", "its", "ia"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["找来", "zhǎo lái", "come looking", "datang mencari"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第25段

    // ===== 第25段 =====
    ["等到", "děng dào", "wait until", "tunggu sehingga"],
    ["狐狸", "hú lí", "fox", "musang"],
    ["走远", "zǒu yuǎn", "walk far away", "berjalan jauh"],
    ["了", "le", "", ""],
    ["，", "", "", ""],
    ["就", "jiù", "then", "lalu"],
    ["一下子", "yī xià zi", "suddenly", "sekali gus"],
    ["从", "cóng", "from", "dari"],
    ["干树枝", "gān shù zhī", "dry branches", "dahan kering"],
    ["堆", "duī", "pile", "timbunan"],
    ["下", "xià", "under", "bawah"],
    ["跳出来", "tiào chū lái", "jump out", "melompat keluar"],
    ["，", "", "", ""],
    ["钻进", "zuān jìn", "burrow into", "masuk ke dalam"],
    ["了", "le", "", ""],
    ["密密", "mì mì", "dense", "rapat"],
    ["的", "de", "", ""],
    ["树林", "shù lín", "woods", "hutan"],
    ["。", "", "", ""],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["能", "néng", "can", "boleh"],
    ["跳着", "tiào zhe", "jumping", "melompat"],
    ["跑", "pǎo", "run", "lari"],
    ["，", "", "", ""],
    ["能", "néng", "can", "boleh"],
    ["跳", "tiào", "jump", "lompat"],
    ["得", "de", "", ""],
    ["很远", "hěn yuǎn", "very far", "sangat jauh"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["跳着", "tiào zhe", "jumping", "melompat"],
    ["跑", "pǎo", "run", "lari"],
    ["的", "de", "", ""],
    ["时候", "shí hou", "when", "apabila"],
    ["，", "", "", ""],
    ["后脚", "hòu jiǎo", "hind legs", "kaki belakang"],
    ["一下下", "yī xià xià", "each time", "setiap kali"],
    ["都", "dōu", "all", "semua"],
    ["踩到", "cǎi dào", "step on", "memijak"],
    ["前脚", "qián jiǎo", "front legs", "kaki depan"],
    ["，", "", "", ""],
    ["这时候", "zhè shí hou", "at this time", "pada masa ini"],
    ["留下", "liú xià", "leave", "tinggalkan"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["就是", "jiù shì", "is", "adalah"],
    ["飞奔", "fēi bēn", "galloping", "berlari kencang"],
    ["的", "de", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["。", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["飞奔", "fēi bēn", "gallop", "berlari kencang"],
    ["起来", "qǐ lái", "up", "naik"],
    ["，", "", "", ""],
    ["人眼", "rén yǎn", "human eye", "mata manusia"],
    ["都", "dōu", "all", "semua"],
    ["看", "kàn", "see", "lihat"],
    ["迷乱", "mí luàn", "dazzled", "keliru"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["路上", "lù shàng", "on the road", "di jalan"],
    ["有", "yǒu", "have", "ada"],
    ["树桩", "shù zhuāng", "tree stump", "tunggul pokok"],
    ["，", "", "", ""],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["侧身", "cè shēn", "turn sideways", "menyamping"],
    ["一绕", "yī rào", "a detour", "satu pusingan"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "lalu"],
    ["过去", "guò qù", "pass", "lalu"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["可", "kě", "but", "tetapi"],
    ["在", "zài", "on", "di"],
    ["树桩", "shù zhuāng", "tree stump", "tunggul pokok"],
    ["上", "shàng", "on", "atas"],
    ["……", "", "", ""],
    ["在", "zài", "on", "di"],
    ["树桩", "shù zhuāng", "tree stump", "tunggul pokok"],
    ["上", "shàng", "on", "atas"],
    ["蹲着", "dūn zhe", "squatting", "mencangkung"],
    ["一只", "yī zhī", "a", "seekor"],
    ["大雕", "dà diāo", "great eagle", "helang besar"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第26段

    // ===== 第26段 =====
    ["大雕", "dà diāo", "The great eagle", "Helang besar"],
    ["一见", "yī jiàn", "as soon as it sees", "sebaik sahaja nampak"],
    ["是", "shì", "is", "ialah"],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["，", "", "", ""],
    ["马上", "mǎ shàng", "immediately", "segera"],
    ["飞起", "fēi qǐ", "fly up", "terbang"],
    ["，", "", "", ""],
    ["追上", "zhuī shàng", "catch up", "mengejar"],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["；", "", "", ""],
    ["一追上", "yī zhuī shàng", "once caught up", "sebaik sahaja mengejar"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "lalu"],
    ["用", "yòng", "use", "menggunakan"],
    ["它", "tā", "its", "ia"],
    ["那双", "nà shuāng", "those pair", "sepasang itu"],
    ["铁钩般", "tiě gōu bān", "like iron hooks", "seperti cangkuk besi"],
    ["的", "de", "", ""],
    ["利爪", "lì zhuǎ", "sharp claws", "kuku tajam"],
    ["去", "qù", "go", "pergi"],
    ["钩", "gōu", "hook", "cangkuk"],
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["脊背", "jǐ bèi", "back", "belakang"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第27段

    // ===== 第27段 =====
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["一头", "yī tóu", "headlong", "terjun"],
    ["钻进", "zuān jìn", "burrow into", "masuk ke dalam"],
    ["了", "le", "", ""],
    ["雪地", "xuě dì", "snow", "salji"],
    ["，", "", "", ""],
    ["大雕", "dà diāo", "eagle", "helang"],
    ["扑过去", "pū guò qù", "pounce over", "menerkam"],
    ["，", "", "", ""],
    ["一对", "yī duì", "a pair", "sepasang"],
    ["大翅膀", "dà chì bǎng", "big wings", "sayap besar"],
    ["在", "zài", "on", "di"],
    ["雪地", "xuě dì", "snow", "salji"],
    ["上", "shàng", "on", "atas"],
    ["啪啪", "pā pā", "flap flap", "puk puk"],
    ["扑扇", "pū shān", "flap", "kepak"],
    ["，", "", "", ""],
    ["把", "bǎ", "", ""],
    ["污泥", "wū ní", "mud", "lumpur"],
    ["都", "dōu", "all", "semua"],
    ["扇", "shān", "flap", "kepak"],
    ["了", "le", "", ""],
    ["起来", "qǐ lái", "up", "naik"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第28段

    // ===== 第28段 =====
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["钻进", "zuān jìn", "burrow into", "masuk ke dalam"],
    ["积雪", "jī xuě", "snow", "salji"],
    ["的", "de", "", ""],
    ["地面", "dì miàn", "ground", "permukaan tanah"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "lalu"],
    ["留下", "liú xià", "leave", "tinggalkan"],
    ["一个", "yī gè", "a", "satu"],
    ["乱糟糟", "luàn zāo zāo", "messy", "bersepah"],
    ["的", "de", "", ""],
    ["雪窝", "xuě wō", "snow pit", "lubang salji"],
    ["。", "", "", ""],
    ["大雕", "dà diāo", "eagle", "helang"],
    ["翅膀", "chì bǎng", "wings", "sayap"],
    ["每", "měi", "every", "setiap"],
    ["一下", "yī xià", "one", "satu"],
    ["拂扇", "fú shān", "flap", "kepak"],
    ["，", "", "", ""],
    ["都", "dōu", "all", "semua"],
    ["在", "zài", "on", "di"],
    ["雪地", "xuě dì", "snow", "salji"],
    ["上", "shàng", "on", "atas"],
    ["留下", "liú xià", "leave", "tinggalkan"],
    ["痕迹", "hén jì", "traces", "kesan"],
    ["，", "", "", ""],
    ["那些", "nà xiē", "those", "itu semua"],
    ["痕迹", "hén jì", "traces", "kesan"],
    ["就", "jiù", "then", "lalu"],
    ["都", "dōu", "all", "semua"],
    ["像", "xiàng", "like", "seperti"],
    ["用", "yòng", "use", "menggunakan"],
    ["手指头", "shǒu zhǐ tou", "finger", "jari"],
    ["抹过", "mǒ guò", "wipe", "mengelap"],
    ["般", "bān", "like", "bagaikan"],
    ["的", "de", "", ""],
    ["光滑", "guāng huá", "smooth", "licin"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第29段

    // ===== 第29段 =====
    ["兔子", "tù zi", "rabbit", "arnab"],
    ["飞奔", "fēi bēn", "gallop", "berlari kencang"],
    ["着", "zhe", "", ""],
    ["，", "", "", ""],
    ["很快", "hěn kuài", "quickly", "cepat"],
    ["钻进", "zuān jìn", "burrow into", "masuk ke dalam"],
    ["了", "le", "", ""],
    ["森林", "sēn lín", "forest", "hutan"],
    ["，", "", "", ""],
    ["脚印", "jiǎo yìn", "footprints", "jejak kaki"],
    ["就", "jiù", "then", "lalu"],
    ["不见了", "bù jiàn le", "disappeared", "hilang"],
    ["。", "", "", ""],
];

// 如果使用模块导出，取消下一行注释；若通过 script 标签引入，则全局可用
// export { lessonTitle, lessonData };
